version: "3.8"

services:
  gerrit:
    image: img.dev.storj.io/gerrit:3.5.0.1-ubuntu20
    build:
      context: .
    environment:
      CANONICAL_WEB_URL: http://localhost:6060
      GITHUB_LOGIN: ${GITHUB_LOGIN:-}
      GITHUB_OAUTH: ${GITHUB_OAUTH:-}
    volumes:
      - ./docker/gerrit/db:/var/gerrit/db
      - ./docker/gerrit/etc:/var/gerrit/etc
      - ./docker/gerrit/cache:/var/gerrit/cache
      - ./docker/gerrit/index:/var/gerrit/index
      - ./docker/gerrit/git:/var/gerrit/git
    ports:
      - "29418:29418"
      - "6060:8080"
